# -*- coding: utf-8 -*-
"""Spectra Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZ47A-0h_AK6jRfrPlG2dl-NvaTxod0g

# **Solving with ColRadPy**
- Below I have the code I used for my project on helium. You will be adjusting all of the following for argon. I've added comments labelled [ADJUST] for the necessary lines to change.
"""

# Import the necessary libraries and functions; remove the comment pound symbol for the !pip for colradpy if it won't download
!pip install git+https://github.com/johnson-c/ColRadPy.git
from colradpy import colradpy
import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import h5py
from google.colab import drive
drive.mount('/content/drive')

os.getcwd() # Gives you the current working directory

"""# **Calculate the predicted ratio given a certain density and temperature**
- Essentially what we are calculating here is the PEC, the "photon emissivity coefficient". This is how many photons per second per cm³ are produced in a plasma for a specific atomic transition; i.e. how many photons of a specific wavelength will be produced under your given plasma conditions.

- The function requires n_e, T_e, n_0, and T_0, where n_0 and T_0 are for the neutral population.

- The goal is to run a series of different values of n_e and T_e (where we approximate a relative value for n_0 and T_0 using the ideal gas law) to get different relative intensity values of each line we want to look at. Then, we will turn those results into ratios to see if the ratios are dependent on n_e and T_e.

- Please note, the following will not work when you run it as
"""

# Note: T values are in [eV] and n values are in [1/cm^3]
def calc_emission(ne, Te, n0, T_He):

# ----------------------------------------------------

# Change this to an ad04 file for argon. Make sure you check the temperature range the file is for, and note that somewhere here!
# Here's a link for a doc describing how/where to find this: (https://docs.google.com/document/d/18KeYFCjWgEnEHpKbymAvac_oJgQi2bW69q2L3q6fwVA/edit?usp=sharing)
    # sys.path.append('.../') # This uses your current working directory
    fil = np.loadtxt('/content/drive/MyDrive/Spectroscopy Data/jj#ar0.dat') # [ADJUST] Insert your file name
    # fil2 = float(fil)
    # from pathlib import Path
    # fil = Path.cwd()  / "Caltech Research Papers/DATA/arlike_mom08#ar0.dat"
    # print("Current working directory:", Path.cwd())
    # print("Expected file path:", fil)
    # print("Exists?", fil.exists())

# ----------------------------------------------------

# The structure for inputs ColRadPy requires is an array of two values as follows.
    e_temp = np.repeat(Te,2) # [eV]
    metastable_states = np.array([0]) # [maybe ADJUST]
    e_density = np.repeat(ne,2) # [1/cm^3]

# ----------------------------------------------------

# This solves the collisional radiative (CR) equations for the given temp and density

    # [ADJUST] to Ar rather than He, i.e. change helium to argon
    # You may need to adjust the "use_recombination" "use_recombination_three_body" etc. to True/False based on the ADF04 file
    # Ar = colradpy(fil, metastable_states, e_temp, e_density, use_recombination = False,
    #                  use_recombination_three_body= True, use_ionization=True, suppliment_with_ecip=True)
    Ar = colradpy(fil, metastable_states, e_temp, e_density,
              use_recombination=False,
              use_recombination_three_body=True,
              use_ionization=True,
              suppliment_with_ecip=True)

    Ar.solve_cr()

# Now, data is stored in the '.data' dictionary; i.e. He.data['']
# Sub-dictionaries like 'wave_air' and 'pecs' can now be accessed. More details on this contained in ColRadPy tutorial in the dictionary
# Here is the link to the accessible terms: https://colradpy.readthedocs.io/en/latest/dictionary.html

# ----------------------------------------------------

# You will need to [ADJUST] each of these!!!
# The following chunk of code extracts the PEC (photon emissivity coefficient). Your goal is to take the below and make it relevant to argon.
# This means, adjust He --> Ar, adjusting the wavelengths found to those for argon (e.g. make pec588 --> pec706)
# You can add more lines or remove lines; whatever you think is best!

    # ------- For the 587.561nm line -------
    #~~~~~~~ Changed to 751.47nm line
    # Find the indices of the line; here, we are accessing values in the .data dictionary we made through solve_cr()
    pec751_ind = np.where((Ar.data['processed']['wave_air']>750) & (Ar.data['processed']['wave_air']<752))[0]

    # Initialize the array for the wavelength
    pec751 = 0

    # Now, we'll use those indices we found for the wavelengths and extract the PECs from the .data dictionary corresponding to those wavelengths
    for ispex in pec751_ind:
        pec751 = Ar.data['processed']['pecs'][ispex,0,:,:].flatten()[0] + pec751 # (pecs, len(metas)+len(metas_ion), user_temp, user dens)

    # ------- For the 667.815nm line -------
    #~~~~~~~ Changed to 801.48nm line
    pec801_ind = np.where((Ar.data['processed']['wave_air']>800) & (Ar.data['processed']['wave_air']<802))[0]
    pec801 = 0
    for ispex in pec801_ind: # A cumulative intensity of all the lines
        pec801 = Ar.data['processed']['pecs'][ispex,0,:,:].flatten()[0]+pec801

    # ------- For the 706.522nm line -------
    #~~~~~~~ Changed to 811.53nm line
    pec812_ind = np.where( (Ar.data['processed']['wave_air'] >811 ) & (Ar.data['processed']['wave_air'] <813 ))[0]
    pec812= 0
    for ispex in pec812_ind: # all lines/transitions at 706 nm added together!
        pec812 = Ar.data['processed']['pecs'][ispex,0,:,:].flatten()[0]+pec812

    # ------- For the 728.135nm line -------
    #~~~~~~~ Changed to 842.46nm line
    pec842_ind = np.where( (Ar.data['processed']['wave_air'] >841) & (Ar.data['processed']['wave_air'] <843 ))[0]
    pec842= 0
    for ispex in pec842_ind: #all lines/transitions at 728 nm added together!
        pec842 = Ar.data['processed']['pecs'][ispex,0,:,:].flatten()[0]+pec842


# ----------------------------------------------------

    # If we have time, we can try and incoporate absorption and opacity calculations because of the following....
    # The PEC gives us a photon rate, but each wavelength value carries a different amount of energy per photon
    # So even though the photon count for two wavelengths could be the same, e.g. a 400nm line contains more energy than a 700nm line
    # Thus, certain effects may play into how the light is radiated.
    # This is a higher order effect we don't need to consider for now, but could be fun if there is time left over!

# ----------------------------------------------------

    return pec751, pec801, pec812, pec842 # [ADJUST] based off the lines you changed above

"""## Example use of the above"""

# Make sure you choose a temperature array within the bounds of the ADF04 file you chose
Te_array = np.linspace(0.5,15,20) # [ADJUST]

# Make sure your density array fits the typical regime of our device (~5e8 to 8e9 [1/cm^3] to be safe)
ne_array = np.linspace(5e8,8e9,20) # [ADJUST]

# Convert to the lines you choose to measure
# Note, the neutral values (n_0 and T_0) will need to be adjusted using the equation PV = NkT --> n0 = P/(k_b*T) to approximate
line751, line801, line812, line842 = calc_emission(ne_array, Te_array,3e12,300)  # [ADJUST]

"""# **Plot the Ratios**
- When you receive actual ratios from your spectra, you can match them to the values you obtained from calc_emission(). Essentially, you are matching the ratio to the given density.
- You'll need to make some of your own custom code to match up the values you get in measurements to the density you calculate through the model.
"""

# Insert your code for plotting here pec751, pec801, pec812, pec842
line751_arr, line801_arr, line812_arr, line842_arr = np.array([]), np.array([]), np.array([]), np.array([])
Te_arr = np.linspace(1,12,50)
for it,Te_dummy in enumerate(Te_arr):
    line751, line801, line812, line842 = calc_emission(3e12,Te_dummy,3e12,300)
    line751_arr = np.append(line751_arr, line751)
    line801_arr = np.append(line801_arr, line801)
    line812_arr = np.append(line812_arr, line812)
    line842_arr = np.append(line842_arr, line842)
    plt.plot(Te_dummy,line751/line842,marker='o',color='mediumorchid')
    plt.plot(Te_dummy,line812/line842, marker = 'o', color = 'blue')
    plt.plot(Te_dummy,line801/line812, marker = 'o', color = 'green')

    if it==0:
        plt.plot(Te_dummy,line751/line842,marker='o',color='mediumorchid', label = '587.5 nm to 728.1 nm')
        plt.plot(Te_dummy,line812/line842, marker = 'o', color = 'blue', label = '706.5 nm to 728.1 nm')
        plt.plot(Te_dummy,line801/line812, marker = 'o', color = 'green', label = '667.8 nm to 706.5 nm')

#plt.plot(Te_arr, line588_arr/line707_arr)
plt.legend()
plt.xlabel("Temperature [eV]")
plt.ylabel("Ratio")
plt.title('Helium Line Dependence on Temperature', fontsize=16, fontweight='bold', color='blue', pad=20)
plt.show()

line751_arr, line801_arr, line812_arr, line842_arr = np.array([]), np.array([]), np.array([]), np.array([])
ne_arr = np.linspace(1e12,1e13,50)
for it,ne_dummy in enumerate(ne_arr):
    line751, line801, line812, line842 = calc_emission(ne_dummy,0.3,1e12,0.06)
    line751_arr = np.append(line751_arr, line751)
    line801_arr = np.append(line801_arr, line801)
    line812_arr = np.append(line812_arr, line812)
    line842_arr = np.append(line842_arr, line842)
    plt.plot(ne_dummy,line751/line812,marker='o',color='mediumorchid')
    plt.plot(ne_dummy,line751/line801, marker = 'o', color = 'blue')
    plt.plot(ne_dummy,line801/line812, marker = 'o', color = 'green')
    if it==0: # Just to make labels nicer
        plt.plot(ne_dummy,line751/line812,marker='o',color='mediumorchid', label = '587.5 nm to 706.5 nm')
        plt.plot(ne_dummy,line751/line801, marker = 'o', color = 'blue', label = '587.5 nm to 667.8 nm')
        plt.plot(ne_dummy,line801/line812, marker = 'o', color = 'green', label = '667.8 nm to 706.5 nm')

plt.plot(ne_arr, line751_arr/line812_arr)
plt.legend()
plt.xlabel("Electron Density [cm^-3]")
plt.ylabel("Ratio")
plt.title('Helium Line Dependence on Electron Density', fontsize=16, fontweight='bold', color='blue', pad=20)

"""# **Some sample plots/examples**
- Below is two samples of code I used to use for my plots for helium if you need some guidance! Feel free to approach it how you would like
- Once you start editing the code for argon above, these plots won't be able to run properly anymore, but the code works pretty well (though it might need some cleaning up)
"""

line588_arr, line668_arr, line707_arr, line728_arr = np.array([]), np.array([]), np.array([]), np.array([])
Te_arr = np.linspace(1,12,50)
for it,Te_dummy in enumerate(Te_arr):
    line588, line668, line707, line728 = calc_emission(1e12,Te_dummy,1e12,0.06)
    line588_arr = np.append(line588_arr, line588)
    line668_arr = np.append(line668_arr, line668)
    line707_arr = np.append(line707_arr, line707)
    line728_arr = np.append(line728_arr, line728)
    plt.plot(Te_dummy,line588/line728,marker='o',color='mediumorchid')
    plt.plot(Te_dummy,line707/line728, marker = 'o', color = 'blue')
    plt.plot(Te_dummy,line668/line707, marker = 'o', color = 'green')

    if it==0:
        plt.plot(Te_dummy,line588/line728,marker='o',color='mediumorchid', label = '587.5 nm to 728.1 nm')
        plt.plot(Te_dummy,line707/line728, marker = 'o', color = 'blue', label = '706.5 nm to 728.1 nm')
        plt.plot(Te_dummy,line668/line707, marker = 'o', color = 'green', label = '667.8 nm to 706.5 nm')

#plt.plot(Te_arr, line588_arr/line707_arr)
plt.legend()
plt.xlabel("Temperature [eV]")
plt.ylabel("Ratio")
plt.title('Helium Line Dependence on Temperature', fontsize=16, fontweight='bold', color='blue', pad=20)
plt.show()

line588_arr, line668_arr, line707_arr, line728_arr = np.array([]), np.array([]), np.array([]), np.array([])
ne_arr = np.linspace(1e12,1e13,50)
for it,ne_dummy in enumerate(ne_arr):
    line588, line668, line707, line728 = calc_emission(ne_dummy,0.3,1e12,0.06)
    line588_arr = np.append(line588_arr, line588)
    line668_arr = np.append(line668_arr, line668)
    line707_arr = np.append(line707_arr, line707)
    line728_arr = np.append(line728_arr, line728)
    plt.plot(ne_dummy,line588/line707,marker='o',color='mediumorchid')
    plt.plot(ne_dummy,line588/line668, marker = 'o', color = 'blue')
    plt.plot(ne_dummy,line668/line707, marker = 'o', color = 'green')
    if it==0: # Just to make labels nicer
        plt.plot(ne_dummy,line588/line707,marker='o',color='mediumorchid', label = '587.5 nm to 706.5 nm')
        plt.plot(ne_dummy,line588/line668, marker = 'o', color = 'blue', label = '587.5 nm to 667.8 nm')
        plt.plot(ne_dummy,line668/line707, marker = 'o', color = 'green', label = '667.8 nm to 706.5 nm')

plt.plot(ne_arr, line588_arr/line707_arr)
plt.legend()
plt.xlabel("Electron Density [cm^-3]")
plt.ylabel("Ratio")
plt.title('Helium Line Dependence on Electron Density', fontsize=16, fontweight='bold', color='blue', pad=20)

# Here's another example if you prefer a style like this.
line588_arr, line668_arr, line707_arr, line728_arr = np.array([]), np.array([]), np.array([]), np.array([])
Te_arr = np.linspace(1,11,50)
for it,Te_dummy in enumerate(Te_arr):
    line588, line668, line707, line728 = calc_emission(1e12,Te_dummy,1e12,0.06)
    line588_arr = np.append(line588_arr, line588)
    line668_arr = np.append(line668_arr, line668)
    line707_arr = np.append(line707_arr, line707)
    line728_arr = np.append(line728_arr, line728)

fig, ax1 = plt.subplots()

line1, = ax1.plot(Te_arr, line588_arr/line668_arr, label = '587.5nm/667.8nm', color = 'blue', linewidth = 2)
ax1.set_xlabel("Tₑ [eV]", fontsize = 18)
ax1.set_ylabel("Line Ratio", fontsize = 18, color = "black")
ax1.tick_params('y', colors='blue', labelsize = 15)

ax2 = ax1.twinx()
line2, = ax2.plot(Te_arr, line588_arr/line707_arr, label = '587.5nm/706.5nm', color = 'darkgreen', linewidth = 2)
ax2.tick_params('y', colors='darkgreen', labelsize = 15)
ax2.yaxis.set_tick_params(color='darkgreen', labelcolor='darkgreen')

lines = [line1, line2]
labels = [line1.get_label(), line2.get_label()]

ax1.legend(lines, labels, loc='lower right', facecolor='white', edgecolor='grey', fontsize=14)
plt.title('Tₑ Dependence of He-I Line Ratios \nat nₑ = 10¹² cm⁻³', fontsize=20, color='black', pad=16)
plt.show()

line588_arr, line668_arr, line707_arr, line728_arr = np.array([]), np.array([]), np.array([]), np.array([])
ne_arr = np.linspace(1e11,1e13,50)
fig, ax1 = plt.subplots()
for it,ne_dummy in enumerate(ne_arr):
    line588, line668, line707, line728 = calc_emission(ne_dummy,0.5,1e12,0.06)
    line588_arr = np.append(line588_arr, line588)
    line668_arr = np.append(line668_arr, line668)
    line707_arr = np.append(line707_arr, line707)
    line728_arr = np.append(line728_arr, line728)

line1, = ax1.plot(ne_arr, line588_arr / line668_arr, label='587.5nm/667.8nm', color='blue', linewidth=2)
ax1.set_xlabel("nₑ [cm⁻³]", fontsize = 18)
ax1.set_ylabel("Line Ratio", fontsize = 18, color = "black")
ax1.tick_params('y', colors='blue', labelsize = 15)

ax2 = ax1.twinx()
line2, = ax2.plot(ne_arr, line588_arr / line707_arr, label='587.5nm/706.5nm', color='darkgreen', linewidth=2)
ax2.tick_params('y', colors='darkgreen', labelsize = 15)
ax2.yaxis.set_tick_params(color='darkgreen', labelcolor='darkgreen')

lines = [line1, line2]
labels = [line1.get_label(), line2.get_label()]
ax1.legend(lines, labels, loc='lower right', facecolor='white', edgecolor='grey', fontsize=14)

plt.title('nₑ Dependence of He-I Line Ratios \nat Tₑ = 0.5 eV', fontsize=20, color='black', pad=16)